'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GYM.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _11__8_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("11 (8)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _end() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("end", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _Exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _Next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property aaa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aaa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Arrow_Next_2_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arrow-Next-2-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bigbg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bigbg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Boxing_Gloves_icon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Boxing-Gloves-icon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_smallBlue_search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_smallBlue_search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CHECK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHECK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property conatin_box_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("conatin-box_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete_1_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete-1_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete_2_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete-2_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dollar_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dollar-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_1_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit-1_19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_2_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit-2_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enter_screen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enter-screen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enter_screen_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enter-screen_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enter_screen_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enter-screen_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enter_screen_031() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enter-screen_031", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enter_screen_03jj_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enter-screen_03jj_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enter_screenkey_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enter-screenkey_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EXIT_2_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EXIT-2_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exit_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ExitRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExitRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FirstRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FirstRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property group_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("group_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property group_add_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("group_add_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hide_Panel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hide_Panel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HP_Explorer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HP-Explorer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HP_Printer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HP-Printer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property I_chat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("I chat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Key() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Key", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Locker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Locker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property main_screen_03Pressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main-screen_03Pressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property main_screen_07Pressed1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main-screen_07Pressed1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property main_screen_09Pressed1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main-screen_09Pressed1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property main_screen_11Pressed1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main-screen_11Pressed1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property main_screen_13Pressed1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main-screen_13Pressed1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property main_screen_15Pressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main-screen_15Pressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property main_screen_17Pressed1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main-screen_17Pressed1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property main_screen_191() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main-screen_191", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property main_screen_19Pressed1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main-screen_19Pressed1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property main_screen_21Pressed1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main-screen_21Pressed1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property main_screen_251() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main-screen_251", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property main_screen_2511() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main-screen_2511", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property main_screen_2512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main-screen_2512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property main_screen_25Pressed1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main-screen_25Pressed1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property main_screen_4123() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main-screen_4123", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property master_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("master_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property master_03Selected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("master_03Selected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property master_05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("master_05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property master_05Selected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("master_05Selected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property master_07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("master_07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property master_09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("master_09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property master_09Selected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("master_09Selected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property master_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("master_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property master_16_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("master_16 copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property master_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("master_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property master_18_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("master_18 copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mzl_xwvncbhw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mzl.xwvncbhw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Paste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paste_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paste_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Previous() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Previous", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rar_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rar_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_18_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_18_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_2_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save-2_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SCISSORS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCISSORS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property server_06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("server_06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Show_Panel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Show_Panel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Symbol_Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Symbol-Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Symbol_Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Symbol-Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Symbol_Help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Symbol-Help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Symbol_Help1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Symbol-Help1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Up_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Up-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property View() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("View", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property without_text_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("without-text_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property without_texte_2_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("without-texte-2_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
